/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DTO.AlunoDTO;
import DAO.AlunoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

/**
 *
 * @author Isa
 */
public class CadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAluno
     */
    public CadastroAluno() {
        initComponents();

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtNome.getText().trim().equals("Nome")) {
                    txtNome.setText(""); // limpa o espaço
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtNome.getText().trim().isEmpty()) {
                    txtNome.setText("Nome"); // restaura o espaço
                }
            }
        });
        txtSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtSobrenome.getText().trim().equals("Sobrenome")) {
                    txtSobrenome.setText(""); // limpa o espaço
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtSobrenome.getText().trim().isEmpty()) {
                    txtSobrenome.setText("Sobrenome"); // restaura o espaço
                }
            }
        });
        txtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtMatricula.getText().trim().equals("Matrícula")) {
                    txtMatricula.setText(""); // limpa o espaço
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtMatricula.getText().trim().isEmpty()) {
                    txtMatricula.setText("Matrícula"); // restaura o espaço
                }
            }
        });
        txtNomeResponsavel.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtNomeResponsavel.getText().trim().equals("Nome do responsável")) {
                    txtNomeResponsavel.setText(""); // limpa o espaço
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtNomeResponsavel.getText().trim().isEmpty()) {
                    txtNomeResponsavel.setText("Nome do responsável"); // restaura o espaço
                }
            }
        });
        txtTelefoneResponsavel.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtTelefoneResponsavel.getText().trim().equals("Número do responsável")) {
                    txtTelefoneResponsavel.setText(""); // limpa o espaço
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtTelefoneResponsavel.getText().trim().isEmpty()) {
                    txtTelefoneResponsavel.setText("Número do responsável"); // restaura o espaço
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        cbxSerie = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        txtTelefoneResponsavel = new javax.swing.JTextField();
        txtNomeResponsavel = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        txtMatricula.setForeground(new java.awt.Color(153, 153, 153));
        txtMatricula.setText("Matrícula");
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome");
        txtNome.setToolTipText("");

        txtSobrenome.setForeground(new java.awt.Color(153, 153, 153));
        txtSobrenome.setText("Sobrenome");

        cbxSerie.setForeground(new java.awt.Color(153, 153, 153));
        cbxSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serie", "1° ano", "2°ano", "3°ano", "4°ano", "5° ano" }));

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtTelefoneResponsavel.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefoneResponsavel.setText("Número do responsável");
        txtTelefoneResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneResponsavelActionPerformed(evt);
            }
        });

        txtNomeResponsavel.setForeground(new java.awt.Color(153, 153, 153));
        txtNomeResponsavel.setText("Nome do responsável");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMatricula)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed

        txtMatricula.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                String caracteres = "0987654321."; // caractere permitido

                // se o caractere pressionado não for válido, consuma o evento
                if (caracteres.indexOf(keyChar) == -1) {
                    e.consume(); // pmpede a inserção do caractere inválido
                }
            }
        });
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastrarAluno();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtTelefoneResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneResponsavelActionPerformed
        txtTelefoneResponsavel.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                String caracteres = "0987654321."; // caractere permitido

                // se o caractere pressionado não for válido, consuma o evento
                if (caracteres.indexOf(keyChar) == -1) {
                    e.consume(); // pmpede a inserção do caractere inválido
                }
            }
        });
    }//GEN-LAST:event_txtTelefoneResponsavelActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        LoginProfessor objLoginView = new LoginProfessor();
        objLoginView.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxSerie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeResponsavel;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtTelefoneResponsavel;
    // End of variables declaration//GEN-END:variables

    
    
    public void CadastrarAluno() {
        String nome;
        String sobrenome;

        
        String matricula;

        String serie;

        String responsavel_nome;
        String responsavel_telefone;

        nome = txtNome.getText();
        sobrenome = txtSobrenome.getText();

        matricula = txtMatricula.getText();

        

        serie = (String) cbxSerie.getSelectedItem();

        responsavel_nome = txtNomeResponsavel.getText();
        responsavel_telefone = txtTelefoneResponsavel.getText();

        AlunoDTO objAlunoDTO = new AlunoDTO();
        objAlunoDTO.setNome(nome);
        objAlunoDTO.setSobrenome(sobrenome);
        objAlunoDTO.setMatricula(matricula);
        

        objAlunoDTO.setSerie(serie);

        objAlunoDTO.setResponsavel_nome(responsavel_nome);
        objAlunoDTO.setResponsavel_telefone(responsavel_telefone);

        AlunoDAO objAlunoDAO = new AlunoDAO();
        objAlunoDAO.cadastrarAluno(objAlunoDTO);

        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");

        LoginProfessor objLoginView = new LoginProfessor();
        objLoginView.setVisible(true);

        dispose();
    }
}
